# Generated by Django 6.0.3 on 2026-03-10 19:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='code',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
