# Generated by Django 4.2.11 on 2026-04-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_meal_fooditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='carbs',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
