# Generated by Django 4.2.11 on 2026-04-03 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workout_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='calories_burned',
        ),
        migrations.AddField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('arms', 'Arms'), ('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('core', 'Core')], max_length=20),
        ),
    ]
