# Generated by Django 4.2.11 on 2026-04-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_passwordreset'),
        ('core', '0005_remove_exercise_calories_burned_workout_status_and_more'),
    ]

    operations = [
    ]
