# Generated by Django 4.2.11 on 2026-04-06 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fooditem_carbs_fooditem_fats_fooditem_protein'),
        ('core', '0006_merge_20260406_2048'),
    ]

    operations = [
    ]
