# Generated by Django 4.2.11 on 2026-04-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20260406_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['muscle_group', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserInjury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.muscle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserEquipmentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('home', 'At Home'), ('gym', 'At Gym'), ('both', 'Both')], max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(related_name='user_profiles', to='core.equipment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='muscle',
            name='muscle_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscles', to='core.musclegroup'),
        ),
        migrations.CreateModel(
            name='TrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, help_text='Step-by-step exercise instructions')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('location', models.CharField(choices=[('home', 'At Home'), ('gym', 'At Gym'), ('both', 'Both Home & Gym')], default='both', max_length=20)),
                ('default_sets', models.PositiveIntegerField(default=3)),
                ('default_reps', models.PositiveIntegerField(default=10)),
                ('default_duration_seconds', models.PositiveIntegerField(blank=True, help_text='For timed exercises', null=True)),
                ('high_impact', models.BooleanField(default=False, help_text='Mark if exercise is high-impact')),
                ('joint_stress', models.CharField(blank=True, help_text='Which joints are stressed (e.g., knees, shoulders)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='core.equipment')),
                ('exercise_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='core.exercisetype')),
                ('muscle_groups', models.ManyToManyField(related_name='training_exercises', to='core.musclegroup')),
                ('primary_muscles', models.ManyToManyField(related_name='primary_exercises', to='core.muscle')),
                ('secondary_muscles', models.ManyToManyField(related_name='secondary_exercises', to='core.muscle')),
            ],
            options={
                'ordering': ['exercise_type', 'name'],
                'indexes': [models.Index(fields=['exercise_type', 'location'], name='core_traini_exercis_a78249_idx'), models.Index(fields=['difficulty'], name='core_traini_difficu_8160d4_idx')],
            },
        ),
    ]
