# Generated by Django 4.2.11 on 2026-04-14 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20260406_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorie_goal', models.PositiveIntegerField(default=2400)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in kg', null=True)),
                ('age', models.PositiveIntegerField(blank=True, help_text='Age in years', null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, null=True)),
                ('primary_goal', models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('strength', 'Strength Training'), ('endurance', 'Endurance & Cardio'), ('flexibility', 'Flexibility & Mobility'), ('general_health', 'General Health & Wellness')], max_length=20, null=True)),
                ('bio', models.TextField(blank=True, help_text='About you and your fitness journey', null=True)),
                ('dietary_preference', models.CharField(blank=True, choices=[('omnivore', 'Omnivore'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('gluten_free', 'Gluten-Free')], max_length=20, null=True)),
                ('home_equipment', models.JSONField(blank=True, default=list, help_text='Available home exercise equipment')),
                ('has_home_gym', models.BooleanField(blank=True, help_text='Does user have home gym setup', null=True)),
            ],
        ),
    ]
