# Generated by Django 4.2.11 on 2026-04-13 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_merge_20260406_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplementDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('supplement_type', models.CharField(choices=[('vitamin', 'Vitamin'), ('mineral', 'Mineral'), ('herb', 'Herbal'), ('protein', 'Protein'), ('amino_acid', 'Amino Acid'), ('other', 'Other')], max_length=20)),
                ('dosage', models.CharField(default='1', max_length=100)),
                ('unit', models.CharField(default='serving', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplementEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('supplement_type', models.CharField(choices=[('vitamin', 'Vitamin'), ('mineral', 'Mineral'), ('herb', 'Herbal'), ('protein', 'Protein'), ('amino_acid', 'Amino Acid'), ('other', 'Other')], max_length=20)),
                ('dosage', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.supplementdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplement_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='supplementdatabase',
            index=models.Index(fields=['name'], name='core_supple_name_5d7809_idx'),
        ),
        migrations.AddIndex(
            model_name='supplementdatabase',
            index=models.Index(fields=['supplement_type'], name='core_supple_supplem_a44698_idx'),
        ),
        migrations.AddIndex(
            model_name='supplemententry',
            index=models.Index(fields=['user', 'date'], name='core_supple_user_id_c1991c_idx'),
        ),
    ]
