# Generated by Django 4.2.11 on 2026-04-15 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed the get_started_profile onboarding'),
        ),
    ]
