# Generated by Django 4.2.11 on 2026-04-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_onboarding_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='social_login_user',
            field=models.BooleanField(default=False, help_text='Whether user came from a social login'),
        ),
    ]
