# Generated by Django 4.2.11 on 2026-04-16 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipment_exercisetype_muscle_musclegroup_userinjury_and_more'),
        ('core', '0011_mealsupplement'),
    ]

    operations = [
    ]
