# Generated by Django 4.2.11 on 2026-04-17 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_drop_legacy_userprofile_table'),
        ('core', '0012_userprofile_social_login_user'),
    ]

    operations = [
    ]
