# Generated by Django 4.2.11 on 2026-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='total_duration_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='Total workout duration in seconds', null=True),
        ),
    ]
