# Generated by Django 4.2.11 on 2026-04-18 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge_20260417_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Number of servings', max_digits=6),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='serving_unit',
            field=models.CharField(choices=[('grams', 'Grams (g)'), ('ounces', 'Ounces (oz)'), ('cups', 'Cups')], default='grams', help_text='Unit of measurement for serving', max_length=20),
        ),
    ]
