# Generated by Django 4.2.11 on 2026-04-18 01:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workout_total_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_progress', to='core.exercise')),
            ],
            options={
                'ordering': ['set_number'],
                'unique_together': {('exercise', 'set_number')},
            },
        ),
    ]
