# Generated by Django 4.2.11 on 2026-04-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_setprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='current_session_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Current session timer in seconds'),
        ),
    ]
