# Generated by Django 4.2.11 on 2026-04-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_workout_current_session_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='goal',
            field=models.CharField(
                choices=[
                    ('weight_loss', 'Weight Loss'),
                    ('muscle_gain', 'Muscle Gain'),
                    ('strength', 'Strength Training'),
                    ('endurance', 'Endurance & Cardio'),
                    ('flexibility', 'Flexibility & Mobility'),
                    ('general_health', 'General Health & Wellness'),
                    ('cardio', 'Cardio Health'),
                ],
                max_length=20,
            ),
        ),
    ]
