# Generated by Django 4.2.11 on 2026-04-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_aichatconversation_aichatmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
