# Generated by Django 4.2.11 on 2026-04-30 04:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0022_rivereventcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="riverevent",
            name="sparked_by",
            field=models.ManyToManyField(
                blank=True, related_name="sparked_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
