# Generated by Django 4.2.11 on 2026-04-30 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_merge_20260428"),
        ("core", "0023_riverevent_sparked_by"),
    ]

    operations = []
